#!/bin/bash
# Copyright (C) 2000-2016 Synology Inc. All rights reserved.

case ${MakeClean} in
	[Yy][Ee][Ss])
		make clean
		;;
esac

# You can use CC CFLAGS LD LDFLAGS CXX CXXFLAGS AR RANLIB READELF STRIP here
#echo "${CC} ${CFLAGS} minimalPkg.c -o minimalPkg.dummy"
#${CC} ${CFLAGS} minimalPkg.c -o minimalPkg.dummy

# Or you can use Makefile to genarate executable.
#MAKE_FLAGS="ENABLE_DEDUPE=1 STATIC_DEDUPE_H=1 ${MAKE_FLAGS}"
echo "make ${MAKE_FLAGS}"
make ${MAKE_FLAGS}
